//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "friends")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub user_one_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub user_two_id: Uuid,
}

impl ActiveModelBehavior for ActiveModel {}
