//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "mailbox")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub user_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub mail_id: Uuid,
    pub read: bool,
    pub archived: bool,
    #[sea_orm(
        belongs_to,
        from = "mail_id",
        to = "mail_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub mail: HasOne<super::mail::Entity>,
    #[sea_orm(
        belongs_to,
        from = "user_id",
        to = "user_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub users: HasOne<super::users::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
