//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub user_id: Uuid,
    #[sea_orm(column_type = "Text", unique)]
    pub name: String,
    #[sea_orm(column_type = "Text", unique)]
    pub email: String,
    #[sea_orm(column_type = "Text")]
    pub password: String,
    #[sea_orm(column_type = "Text")]
    pub salt: String,
    pub created: DateTimeWithTimeZone,
    #[sea_orm(has_many)]
    pub inventory_items: HasMany<super::inventory_item::Entity>,
    #[sea_orm(has_many)]
    pub player_effects: HasMany<super::player_effects::Entity>,
    #[sea_orm(has_one)]
    pub stats: HasOne<super::stats::Entity>,
    #[sea_orm(has_many, via = "mailbox")]
    pub mail: HasMany<super::mail::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
