//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "fish_caught_bait")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub user_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub fish_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub bait_id: i32,
    #[sea_orm(
        belongs_to,
        from = "(user_id, fish_id)",
        to = "(user_id, fish_id)",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub fish_caught: HasOne<super::fish_caught::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
