//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "fish_caught")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub user_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub fish_id: i32,
    pub amount: i32,
    pub max_length: i32,
    pub first_caught: Date,
    #[sea_orm(has_many)]
    pub fish_caught_areas: HasMany<super::fish_caught_area::Entity>,
    #[sea_orm(has_many)]
    pub fish_caught_baits: HasMany<super::fish_caught_bait::Entity>,
    #[sea_orm(
        belongs_to,
        from = "user_id",
        to = "user_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub stats: HasOne<super::stats::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
