//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::fish_caught::Entity as FishCaught;
pub use super::fish_caught_area::Entity as FishCaughtArea;
pub use super::fish_caught_bait::Entity as FishCaughtBait;
pub use super::friend_requests::Entity as FriendRequests;
pub use super::friends::Entity as Friends;
pub use super::inventory_item::Entity as InventoryItem;
pub use super::mail::Entity as Mail;
pub use super::mailbox::Entity as Mailbox;
pub use super::player_effects::Entity as PlayerEffects;
pub use super::stats::Entity as Stats;
pub use super::users::Entity as Users;
