//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "stats")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub user_id: Uuid,
    pub selected_rod: Option<Uuid>,
    pub selected_bait: Option<Uuid>,
    pub xp: i32,
    pub coins: i32,
    pub bucks: i32,
    pub total_playtime: i32,
    #[sea_orm(has_many)]
    pub fish_caughts: HasMany<super::fish_caught::Entity>,
    #[sea_orm(
        belongs_to,
        from = "user_id",
        to = "user_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub users: HasOne<super::users::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
